apiVersion: batch/v1
kind: Job
metadata:
  name: quantum-safe-demo
  namespace: quantum-safe-mesh
  labels:
    app: demo-client
    component: demo
spec:
  template:
    metadata:
      labels:
        app: demo-client
        component: demo
    spec:
      restartPolicy: OnFailure
      containers:
      - name: demo-client
        image: quantum-safe-mesh/demo:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: GATEWAY_URL
          value: "http://gateway-service.quantum-safe-mesh.svc.cluster.local:8081"
        - name: AUTH_URL
          value: "http://auth-service.quantum-safe-mesh.svc.cluster.local:8080"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
  backoffLimit: 3